version: "3.8"
services:
  app:
    image: authusers
    build:
      context: .
      dockerfile: Dockerfile
    ports:
        "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=pre
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/auth?useSSL=false&serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=josedabh
      - SPRING_DATASOURCE_PASSWORD=OMEGA03boli+
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=OMEGA03boli+
      - MYSQL_DATABASE=auth
      - MYSQL_USER=josedabh
      - MYSQL_PASSWORD=OMEGA03boli+
    ports:
      - "3306:3306"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql