# Base de datos
spring.datasource.url=jdbc:mysql://localhost:3306/auth?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=123456
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JWT
jwt.secret=3ac5bfb24b7969eda29de03ca03f0c107d3063047950735ce12fdab8b466aae2
jwt.expiration=10

# Port
server.port=8081