# Base de datos (Render, AWS, DigitalOcean, etc.)
spring.datasource.url=jdbc:mysql://mysql:3306/auth?useSSL=false&serverTimezone=UTC
spring.datasource.username=josedabh
spring.datasource.password=OMEGA03boli+
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JWT
jwt.secret=70c41a3ecfe4bfa6daeca2716c3d3e5f273bada72eb97c4e8e7807e6da08e616
jwt.expiration=30

server.port:8080