spring:
  application:
    name: authusers
  profiles:
    active: dev
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.MySQL8Dialect
      ddl-auto: update
    show-sql: true
    open-in-view: true

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /index.html

logging:
  level:
    root: INFO